version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python manage.py runserver 0.0.0.0:8002'
    ports:
      - 8002:8002
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mariadb:10.4 # mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: orthogra_db1
      MYSQL_USER: orthogra_1 #root
      MYSQL_PASSWORT: mZGK37Gt1cGBmx8F #test
      MYSQL_ROOT_PASSWORD: mZGK37Gt1cGBmx8F #test
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33068:3306
